Support overlays and events
BlazorComponent/MASA.Blazor pull request #1029
Opened 2023-02-22 02:10 UTC by msnoshain

# Description

- Supoort all the map events
- Supoort main map overlays (Label, Marker, Circle, Polyline and Polygon)
- Add docs for new features

2023-02-24 03:45 UTC, capdiem requested changes

2023-02-24 03:45 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +                StateHasChanged();
应该不用调StateHasChanged

2023-02-24 03:45 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +        public async ValueTask<bool> Contains(MBaiduOverlay overlay)
```suggestion
        public async ValueTask<bool> ContainsOverlayAsync(MBaiduOverlay overlay)
```

2023-02-24 03:45 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/Overlays/MBaiduOverlay.cs
> +    public abstract class MBaiduOverlay : BComponentBase
```suggestion
    public abstract class BaiduOverlayBase : BComponentBase
```

2023-02-24 03:45 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/BaiduMapJSObjectReferenceProxy.cs
> +            };
使用[ switch 表达式](https://learn.microsoft.com/zh-cn/dotnet/csharp/language-reference/operators/switch-expression)。

2023-02-24 03:45 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/BaiduMapJSObjectReferenceProxy.cs
> +        await InvokeVoidAsync("addOverlay", overlay.OverlayJSObjectRef);
```suggestion
        else
        {
            await InvokeVoidAsync("addOverlay", overlay.OverlayJSObjectRef);
        }
```

2023-02-24 03:45 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/Overlays/MBaiduCircle.cs
> +        public string StrokeColor { get; set; } = "blue";
我看很多地方用的blue，有什么说法吗？如果没有不设置颜色可不可以？一定要设置那建议使用内置的 primary secondary 之类的。

2023-02-24 03:45 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/Overlays/MBaiduCircle.cs
> +        public float Radius { get; set; }
Radius后期如果变了咋办？现在似乎不会重新渲染。其他参数也是

2023-02-24 03:45 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/Overlays/MBaiduCircle.cs
> +            RenderConditions = () => Radius > 0;
RenderConditions我觉得有点多余，如果变了Radius=0传给js处理也没关系。

2023-02-24 05:36 UTC, msnoshain commented on src/Masa.Blazor/Components/Map/BaiduMap/BaiduMapJSObjectReferenceProxy.cs
> +        if (_owner.OnMoving.HasDelegate) events.Add("moveend");
对，写错了😂

2023-02-24 05:43 UTC, msnoshain commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +                StateHasChanged();
不写的话覆盖物就不会渲染

2023-02-24 07:36 UTC, msnoshain commented on src/Masa.Blazor/Components/Map/BaiduMap/BaiduMapJSObjectReferenceProxy.cs
> +        events.Add("zoomend");
moving和zoomed默认开启监听，这样用户用鼠标移动或者缩放地图的时候Center和Zoom才能跟着变

2023-02-28 14:40 UTC, capdiem requested changes

2023-02-28 14:40 UTC, capdiem commented on docs/Masa.Blazor.Docs/Examples/components/baidumaps/ZoomAndMove.razor
> +           Center="_center" />
Zoom和Center会被内部修改吧，那么应该也要支持`@bind-{Prop}`才对 😮。哈哈真麻烦。
或者不要用[Parameter]，仅能通过 MBaiduMap的 ref 修改。

2023-03-09 03:53 UTC, capdiem requested changes

2023-03-09 03:53 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +            await ZoomChanged.InvokeAsync(Zoom);
```suggestion
            if (ZoomChanged.HasDelegate)
            {
                await ZoomChanged.InvokeAsync(zoom);
            }
```

2023-03-09 07:44 UTC, capdiem approved these changes
LGTM.

2023-03-09 07:50 UTC, merged