feat: add navigation bar to document home page
BlazorComponent/MASA.Blazor pull request #1033
Opened 2023-02-22 15:23 UTC by MapleWithoutWords

feat: add navigation bar to document home page

2023-02-22 16:39 UTC, doddgu commented
@codding-y PTAL

2023-02-24 05:36 UTC, capdiem requested changes

2023-02-24 05:36 UTC, capdiem commented on docs/Masa.Docs.Shared/Pages/Index.razor
>  @layout MainLayout
改成继承 BaseLayout，结构需要改下：
``` html
<MNavigation></MNavigation>
<MMain>
    <MContainer>
        <MResponsive>
</MMain>
```

2023-02-24 05:36 UTC, capdiem commented on docs/Masa.Docs.Shared/Pages/Index.razor
> +                       Id="nav-drawer1"
应该不需要。

2023-02-24 05:36 UTC, capdiem commented on docs/Masa.Docs.Shared/Pages/Index.razor
> +            <MListItem>
UI没有还原，参考是NavigatoinDrawer使用的 `DefaultList`

2023-02-24 05:36 UTC, capdiem commented on docs/Masa.Docs.Shared/Pages/Index.razor
> +                <div class="project" id="link_@project">
```suggestion
                <div class="project" id="@project">
```

2023-02-24 05:36 UTC, capdiem commented on docs/Masa.Docs.Shared/Pages/Index.razor
> +            <div class="project" id="link_getting-started">
```suggestion
            <div class="project" id="getting-started">
```

2023-02-24 05:36 UTC, capdiem commented on docs/Masa.Docs.Shared/Pages/Index.razor
> +        new VersionSelectItem("1.0","1.0"),
如果 value 和 text 都是一样的，就不用搞个类出来，直接用 List<string>

2023-02-24 05:36 UTC, capdiem commented on docs/Masa.Docs.Shared/Pages/Index.razor
> +
先删除。

2023-02-24 05:36 UTC, capdiem commented on docs/Masa.Docs.Shared/Pages/Index.razor
> +    }
直接使用 List<string>

2023-02-26 02:41 UTC, doddgu requested changes

2023-02-26 02:41 UTC, doddgu commented on docs/Masa.Docs.Shared/Pages/Index.razor
> +        public VersionSelectItem(string label, string value)
Add blank line.

2023-02-27 03:25 UTC, MapleWithoutWords commented
already correction

2023-03-01 01:36 UTC, capdiem requested changes

2023-03-01 01:36 UTC, capdiem commented on docs/Masa.Docs.Shared/Pages/Index.razor
> +<MMain>
<MMain>放在 <NavigationDrawer>后面的<MContainer>外面：
<MNavigationDrawer />
<MMain>
  <MContainer>
  <MContainer>
</MMain>

2023-03-02 03:17 UTC, closed without merging