feat:Fix cron expression initialization
BlazorComponent/MASA.Blazor pull request #1054
Opened 2023-03-03 10:13 UTC by kogel-net

# Description

Fix cron expression initialization

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2023-03-04 03:35 UTC, capdiem requested changes

2023-03-04 03:35 UTC, capdiem commented on src/Masa.Blazor/Presets/Cron/Items/CronItem.razor.cs
> -            _selectWeekNumber = WeekNumbers.First;
这些初始化丢了没关系吗？

2023-03-04 03:35 UTC, capdiem commented on src/Masa.Blazor/Presets/Cron/Items/CronItem.razor
> +                    @I18n.T($"$masaBlazor.cron.range.from") <MTextField Value="_cronItemData.PeriodStart" HideDetails="true" Outlined Dense ValueChanged="OnPeriodStartChanged" Type="number" NumberPro
CronItem.razor 文件格式化一下。

2023-03-08 11:23 UTC, doddgu approved these changes
LGTM

2023-03-09 07:29 UTC, capdiem approved these changes
LGTM

2023-03-09 07:49 UTC, merged