feat:add navigation bar to document home page
BlazorComponent/MASA.Blazor pull request #1055
Opened 2023-03-03 11:00 UTC by MapleWithoutWords

![image](https://user-images.githubusercontent.com/38368335/222703768-a055944d-e30a-4e5b-8805-1454e44f2224.png)

2023-03-04 03:25 UTC, capdiem commented
@MapleWithoutWords UI部分我帮你修改了一下，另外还有两个功能需要做：
1. 移动端 NavigationDrawer 会隐藏，隐藏后应该通过左上角的 按钮再显示出来。
2. 更改URL的hash能自动定位。

2023-03-04 03:32 UTC, MapleWithoutWords commented
> Refer

好的，收到

2023-03-06 03:39 UTC, MapleWithoutWords commented
> @MapleWithoutWords UI部分我帮你修改了一下，另外还有两个功能需要做：
> 
> 1. 移动端 NavigationDrawer 会隐藏，隐藏后应该通过左上角的 按钮再显示出来。
> 2. 更改URL的hash能自动定位。

already compeleted. effect image:
<img width="1011" alt="无标题" src="https://user-images.githubusercontent.com/38368335/223014370-661a0c24-08bc-4cb1-99e6-6d48491679c2.png">
<img width="1011" alt="无标题2" src="https://user-images.githubusercontent.com/38368335/223014383-d50e1bcc-a4ba-4615-add8-3973388a7e04.png">

2023-03-06 03:49 UTC, MapleWithoutWords commented
mobile terminal navigation bar width property already change to 300px
![image](https://user-images.githubusercontent.com/38368335/223015352-0da12322-3eb0-4814-a642-4fc589a74d0e.png)

2023-03-06 13:37 UTC, capdiem requested changes

2023-03-06 13:37 UTC, capdiem commented on docs/Masa.Docs.Shared/Components/Menus/MobileIndexNavMenuList.razor
> +                   Temporary>
用一个NavigationDrawer不就好了，参考 DocLayout。

2023-03-07 04:21 UTC, MapleWithoutWords commented on docs/Masa.Docs.Shared/Components/Menus/MobileIndexNavMenuList.razor
> +                   Temporary>
已修改

2023-03-07 05:50 UTC, capdiem approved these changes

2023-03-07 05:50 UTC, merged