add Monaco  Comman ，
BlazorComponent/MASA.Blazor pull request #1073
Opened 2023-03-11 05:31 UTC by 239573049

# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

2023-03-13 08:36 UTC, doddgu commented
@capdiem PTAL

2023-03-13 09:11 UTC, capdiem requested changes

2023-03-13 09:11 UTC, capdiem commented on src/Masa.Try.Shared/Pages/Index.razor.cs
> +    private MMonacoEditor _Monaco;
```suggestion
    private MMonacoEditor _monaco;
```

2023-03-13 09:11 UTC, capdiem commented on src/Masa.Try.Shared/Pages/Index.razor.cs
> +        await _Monaco.AddCommand(2097, DotNetObjectReference.Create(this), nameof(RunCode));
`DotNetObjectReference.Create(this)` needs dispose

2023-03-14 01:59 UTC, capdiem requested changes

2023-03-14 02:33 UTC, capdiem requested changes

2023-03-14 02:33 UTC, capdiem commented on src/Masa.Try.Shared/Pages/Index.razor.cs
> +        DotNetObject.Dispose();
```suggestion
        _objRef.Dispose();
```

2023-03-14 06:36 UTC, capdiem approved these changes

2023-03-14 06:36 UTC, merged