fix(Alert): Fix the problem that the border of alert is right angle
BlazorComponent/MASA.Blazor pull request #1087
Opened 2023-03-15 09:15 UTC by codding-y

![image](https://user-images.githubusercontent.com/42963214/225265139-c39c03ba-64ba-421a-9d6b-8c41e6940435.png)
resolved:
![image](https://user-images.githubusercontent.com/42963214/225265637-2516bf8c-5151-4256-ae0c-491fe0f3f905.png)

2023-03-15 10:29 UTC, doddgu commented
@capdiem PTAL

2023-03-15 14:57 UTC, capdiem requested changes

2023-03-15 14:57 UTC, capdiem commented on src/Masa.Blazor/Components/Alert/MAlert.cs
>              };
这写法看着有点别扭，再搞个`AlertBorderClass`方法就舒服多了。要不改改？

2023-03-16 02:03 UTC, capdiem approved these changes

2023-03-16 02:03 UTC, merged