fix:navigation bar will not follow scroll bar scroll
BlazorComponent/MASA.Blazor pull request #1112
Opened 2023-03-20 15:32 UTC by MapleWithoutWords

https://user-images.githubusercontent.com/38368335/226389350-08453bed-5cab-4c56-bdcd-357f45014c71.mp4

2023-03-21 07:02 UTC, doddgu requested changes

2023-03-21 07:02 UTC, doddgu commented on docs/Masa.Docs.Shared/Pages/Index.razor
> +                       @onclick:preventDefault
format code

2023-03-21 07:02 UTC, doddgu commented on docs/Masa.Docs.Shared/Pages/Index.razor
> +                       class="m-list-item m-list-item--link @GenClass(project)"
format code

2023-03-21 10:05 UTC, capdiem requested changes

2023-03-21 10:05 UTC, capdiem commented on docs/Masa.Docs.Shared/wwwroot/js/docs.js
> +window.registerWindowScrollEvent = function (dotnet, className) {
直接传 cssSelector 不就简单了吗？

2023-03-21 10:05 UTC, capdiem commented on docs/Masa.Docs.Shared/Shared/Toc.razor
> +                <li class="pl-3 text-body-2 py-1 font-weight-regular @GenClass(item) scroll-change-hash">
```suggestion
                <li class="pl-3 text-body-2 py-1 font-weight-regular @GenClass(item) toc-li">
```

2023-03-21 10:05 UTC, capdiem commented on docs/Masa.Docs.Shared/Pages/Index.razor
> +                <MListItem Value="@("#getting-started")" Class="scroll-change-hash" OnClick='() => ScrollIntoView("getting-started")' Attributes="@(new Dictionary<string,object>{ {"href" , "#getting-
```suggestion
                <MListItem Value="@("#getting-started")" Class="doc-list-nav--item-hash" OnClick='() => ScrollIntoView("getting-started")' Attributes="@(new Dictionary<string,object>{ {"href" , "#getting-started" }})">
```

2023-03-22 06:13 UTC, capdiem approved these changes

2023-03-23 05:18 UTC, merged