feat(docs): support Full text retrieval (Algolia)
BlazorComponent/MASA.Blazor pull request #1126
Opened 2023-03-22 10:52 UTC by xyfy

support Full text retrieval (Algolia) 

#1125

2023-03-23 07:23 UTC, doddgu requested changes

2023-03-23 07:23 UTC, doddgu commented on docs/Masa.Docs.Indexing/AlgoliaIndexBuilder.cs
> +                throw new DirectoryNotFoundException($"can not found directory `{path}`,please check config");
can -> Can. and add a space after `,`, and add `.` at last.

2023-03-23 07:23 UTC, doddgu commented on docs/Masa.Docs.Indexing/AlgoliaIndexBuilder.cs
> +        private IndexSettings GetIndexSetting()
Add blank line.

2023-03-23 07:23 UTC, doddgu commented on docs/Masa.Docs.Indexing/AlgoliaIndexBuilder.cs
> +                _logger.LogInformation($"to create index with {datas.Count()} pages");
to create -> Create

2023-03-23 07:23 UTC, doddgu commented on docs/Masa.Docs.Indexing/AlgoliaIndexBuilder.cs
> +                _logger.LogInformation($"created index complete");
created -> Created

2023-03-23 07:23 UTC, doddgu commented on docs/Masa.Docs.Indexing/AlgoliaOption.cs
> +        public string IndexPrefix { get; set; } = "xyfy_";
xyfy_ ?

2023-03-23 07:23 UTC, doddgu commented on docs/Masa.Docs.Indexing/Data/Record.cs
> +    public Record(string lang, string docUrl, string rootName, RecordType type, int level, int position, int pageRank = 0)
After Properties.

2023-03-23 07:23 UTC, doddgu commented on docs/Masa.Docs.Indexing/Data/Record.cs
> +    public void ClonePrerecord(Record fromRecord)
After constructor.

2023-03-23 07:23 UTC, doddgu commented on docs/Masa.Docs.Indexing/Data/RecordRoot.cs
> +        public RecordRoot(string indexName)
After properties.

2023-03-23 07:23 UTC, doddgu commented on docs/Masa.Docs.Indexing/Data/RecordVersion.cs
> +    public enum RecordType
A single file.

2023-03-23 07:23 UTC, doddgu commented on docs/Masa.Docs.Indexing/IndexHelper.cs
> +        public static string CharCodeAt(this string character, int index)
Add blank line.

2023-03-23 07:23 UTC, doddgu commented on docs/Masa.Docs.Indexing/IndexHelper.cs
> +                throw new ArgumentNullException(paramName, "argument is null,please check config");
argument -> Argument, and add a space after `,`, and add a `.` at last.

2023-03-23 07:23 UTC, doddgu commented on docs/Masa.Docs.Indexing/IndexHelper.cs
> +                //取出二进制编码内容
English comment.

2023-03-23 07:23 UTC, doddgu commented on docs/Masa.Docs.Indexing/IndexHostedService.cs
> +
Remove a blank line.

2023-03-23 07:23 UTC, doddgu commented on docs/Masa.Docs.Indexing/IndexHostedService.cs
> +
Remove a bliank line, and remove the commented code.

2023-03-23 07:23 UTC, doddgu commented on docs/Masa.Docs.Indexing/IndexHostedService.cs
> +            //StartDocServer();
Remove the commented code.

2023-03-23 07:23 UTC, doddgu commented on docs/Masa.Docs.Indexing/Masa.Docs.Indexing.csproj
> +    <!--<PackageReference Include="Selenium.WebDriver" Version="4.8.1" />-->
Remove it.

2023-03-23 07:23 UTC, doddgu commented on docs/Masa.Docs.Indexing/Properties/launchSettings.json
> +        "MASA_ALGOLIA_APIKEY": "37ed20bfb379156e2e25ef0b66af9b52"
?

2023-03-23 07:23 UTC, doddgu commented on docs/Masa.Docs.Indexing/appsettings.json
> +    "IndexPrefix": "xyfy_local_",
?

2023-03-23 07:23 UTC, doddgu commented on docs/Masa.Docs.Indexing/appsettings.json
> +    "RootDocsPath": "D:\\Source\\Masa\\Stack\\src\\MASA.Blazor\\docs",
?

2023-03-23 07:23 UTC, doddgu commented on docs/Masa.Docs.Indexing/appsettings.json
> +    "ApplicationId": "TE02P6CBRV",
?

2023-03-23 07:23 UTC, doddgu commented on docs/Masa.Docs.Shared/Components/Search.razor
> +
Remove a blank line.

2023-03-23 07:23 UTC, doddgu commented on docs/Masa.Docs.Shared/Shared/AppBarItems.razor
> +
Remove a blank line.

2023-03-23 08:20 UTC, xyfy commented on .github/workflows/doc-index.yml
> +      - main
this workflow is for dev-doc-site only

2023-03-23 09:01 UTC, doddgu requested changes

2023-03-23 09:01 UTC, doddgu commented on docs/Masa.Docs.Indexing/Program.cs
> +        var x = hostContext.Configuration.GetSection(AlgoliaOptions.Position);
x?

2023-03-23 09:59 UTC, doddgu requested changes

2023-03-23 09:59 UTC, doddgu commented on docs/Masa.Docs.Indexing/Program.cs
> +           .AddEnvironmentVariables(x=>x.Prefix= "MASA_")
code format.

2023-03-24 01:42 UTC, capdiem requested changes

2023-03-24 01:42 UTC, capdiem commented on docs/Masa.Docs.Shared/Components/Search.razor
> +    }
按目前的逻辑，`ReInit=false`是不会更改父组件的`_reInitSearch`的值的，你需要调 `ReInitChanged.InvokeAsync`更新。但是有个更简单的方法，把`InitDocSearchAsync`改为public method，然后父组件通过`@ref`的方式直接调这个方法就行了。

2023-03-24 01:42 UTC, capdiem commented on docs/Masa.Docs.Shared/Components/Search.razor
> +            });
不用InvokeAsync，StateHasChanged要在Init方法后面。但如果你用publich method的方式，就不用维护ReInit的状态，就不用StateHasChanged。

2023-03-24 01:42 UTC, capdiem commented on docs/Masa.Docs.Shared/Components/Search.razor
> +    private async Task InitDocSearchAsycn()
InitDocSearchAsycn -> InitDocSearchAsync

2023-03-24 02:52 UTC, capdiem requested changes

2023-03-24 02:52 UTC, capdiem commented on docs/Masa.Docs.Shared/Shared/AppBarItems.razor
> +    private Search? _AlgoliaSearch;
```suggestion
    private Search? _algoliaSearch;
```

2023-03-24 02:52 UTC, capdiem commented on docs/Masa.Docs.Shared/Shared/AppBarItems.razor
> +    private bool _reInitSearch { get; set; }
```suggestion
```

2023-03-24 02:52 UTC, capdiem commented on docs/Masa.Docs.Shared/Components/Search.razor
> +@if (MasaBlazor?.Breakpoint?.Mobile is not true)
```suggestion

@if (MasaBlazor?.Breakpoint?.Mobile is not true)
```

2023-03-24 02:52 UTC, capdiem commented on docs/Masa.Docs.Shared/Components/Search.razor
> +            StateHasChanged();
```suggestion
```

2023-03-24 02:57 UTC, capdiem requested changes

2023-03-24 02:57 UTC, capdiem commented on docs/Masa.Docs.Shared/Shared/AppBarItems.razor
> +        await _AlgoliaSearch!.InitDocSearchAsync();
```suggestion
        await _algoliaSearch!.InitDocSearchAsync();
```

2023-03-24 03:52 UTC, capdiem approved these changes

2023-03-24 03:53 UTC, capdiem commented on docs/Masa.Docs.Shared/wwwroot/js/docs.js
不要格式化整个文件啊，js是以两个空格作为一个tab。

2023-03-24 03:54 UTC, capdiem requested changes

2023-03-24 03:54 UTC, capdiem commented on docs/Masa.Docs.Shared/wwwroot/js/docs.js
不要格式化整个文件啊，js是以两个空格作为一个tab。

2023-03-24 05:07 UTC, capdiem approved these changes

2023-03-27 05:03 UTC, doddgu approved these changes

2023-03-27 05:03 UTC, merged