refactor(docs): refactor algolia index builder and search
BlazorComponent/MASA.Blazor pull request #1144
Opened 2023-03-27 09:29 UTC by xyfy

2023-03-27 11:10 UTC, doddgu requested changes

2023-03-27 11:10 UTC, doddgu commented on docs/Masa.Docs.Shared/Shared/AppBar.razor
> +    [CascadingParameter(Name = "project")]
project? Project?

2023-03-27 16:14 UTC, capdiem requested changes

2023-03-27 16:14 UTC, capdiem commented on docs/Masa.Docs.Indexing/AlgoliaIndexBuilder.cs
>                          var records = PraseDocument(content, docUrl, language, project);
typo: PraseDocument -> ParseDocument

2023-03-27 16:14 UTC, capdiem commented on docs/Masa.Docs.Shared/Shared/AppBarItems.razor
> +    public string? Env { get; set; } = null!;
`string?` 和 `null!` 不冲突吗？

2023-03-27 16:14 UTC, capdiem commented on docs/Masa.Docs.Indexing/AlgoliaIndexBuilder.cs
> +                Console.WriteLine("{0}\t{1}\t{2}\n{3}\n", node.GetType().Name, docUrl, position, content);
为啥这里不用 _logger？

2023-03-27 23:47 UTC, xyfy commented on docs/Masa.Docs.Indexing/AlgoliaIndexBuilder.cs
> +                Console.WriteLine("{0}\t{1}\t{2}\n{3}\n", node.GetType().Name, docUrl, position, content);
这个只想在控制台看吧，用_logger也行

2023-03-28 01:12 UTC, capdiem approved these changes
LGTM

2023-03-28 01:23 UTC, merged