Feature/editor
BlazorComponent/MASA.Blazor pull request #353
Opened 2022-03-25 11:08 UTC by wzh425

2022-03-26 05:46 UTC, capdiem requested changes

2022-03-26 05:46 UTC, capdiem commented on src/Masa.Blazor/Components/Editor/MEditor.cs
> +            var objRef = DotNetObjectReference.Create(this);
Missing dispose of DotNetObjectReference：应该把objRef声明定义在外面，并在Dispose()释放掉。

2022-03-26 05:46 UTC, capdiem commented on src/Masa.Blazor/Components/Editor/MEditor.cs
> +            await CreateEditor();
不应该每次Render都去创建一个新的Quill实例。
我看了下Quill的实例方法，也就Toolbar、placeholder、readonly和theme属性发生变化时才需要创建新的实例。因此你可以监听这些属性的变化控制是否创建新的实例。
默认应该只在firstRender内创建Quill实例。
另外readonly可以通过实例的disbale和enable方法来控制，readonly也不用去监听。

2022-03-28 09:00 UTC, wzh425 commented on src/Masa.Blazor/Components/Editor/MEditor.cs
> +            await CreateEditor();
我这里是在firstRender下才创建Quill实例

2022-03-28 10:59 UTC, capdiem requested changes

2022-03-28 10:59 UTC, capdiem commented on src/Doc/Masa.Blazor.Doc/Demos/Components/Editor/props/readOnly.md
> +  en-US: readOnly
Readonly

2022-03-28 10:59 UTC, capdiem commented on src/Doc/Masa.Blazor.Doc/Demos/Components/Editor/props/theme.md
> +  en-US: theme
英文的title开头大写

2022-03-28 10:59 UTC, capdiem commented on src/Doc/Masa.Blazor.Doc/Demos/Components/Editor/props/toolBar.md
> +  en-US: toolBar
Toolbar

2022-03-28 10:59 UTC, capdiem commented on src/Masa.Blazor/Components/Editor/MEditor.cs
> +        [JSInvokable]
方法之间为为什么没有空行？

2022-03-28 12:36 UTC, capdiem approved these changes
GLTM. @doddgu

2022-03-29 02:22 UTC, doddgu approved these changes
LGTM

2022-03-29 02:22 UTC, merged