feat(component): TextField component supper number type
BlazorComponent/MASA.Blazor pull request #361
Opened 2022-03-30 03:56 UTC by gavin1ee

feat(component): TextField component supper number type

2022-04-02 06:48 UTC, capdiem requested changes

2022-04-02 06:48 UTC, capdiem commented on src/Masa.Blazor/Components/TextField/MTextField.cs
> +                if (BindConverter.TryConvertToDecimal(InternalValue.ToString(), System.Globalization.CultureInfo.InvariantCulture, out var value))
不需要`ToString()`吧？如果没有必要，下面的`ToString()`都可删除。

2022-04-02 06:48 UTC, capdiem commented on src/Masa.Blazor/Components/TextField/MTextField.cs
> +            if (NumberProps != null)
NumberProps?.Invoke(Props)

2022-04-02 06:48 UTC, capdiem commented on src/Masa.Blazor/Components/TextField/MTextField.cs
> +            //_cancellationTokenSource?.Cancel();
注释先删掉。

2022-04-02 06:48 UTC, capdiem commented on src/Masa.Blazor/Components/TextField/MTextField.cs
> +                TValue retValue;
retValue -> returnValue

2022-04-02 06:48 UTC, capdiem commented on src/Masa.Blazor/Components/TextField/MTextField.cs
> +                if (Props.Max !=null && value > Props.Max)
格式化一下

2022-04-02 06:48 UTC, capdiem commented on src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MAutocomplete.en-US.json
> +    {
因为 Autocomplete Cascader FileInput Select Textarea 都继承自 TextField，会导致 NumberProps 这个Parameter也会暴露出去。除了TextField，其他组件应该不需要 NumberProps吧？

2022-04-06 06:47 UTC, capdiem approved these changes
LGTM. @doddgu

2022-04-07 09:40 UTC, doddgu approved these changes
LGTM

2022-04-10 01:33 UTC, merged