feat(component): Add Toast component
BlazorComponent/MASA.Blazor pull request #383
Opened 2022-04-01 11:46 UTC by gavin1ee

2022-04-11 02:51 UTC, capdiem requested changes

2022-04-11 02:51 UTC, capdiem commented on src/Masa.Blazor/Popup/Components/Toast/Toast.razor.cs
> +        public Task HandleOnCloseAsync(ToastConfig args)
Rename 'args'

2022-04-11 02:51 UTC, capdiem commented on src/Masa.Blazor/Popup/Components/Toast/Toast.razor.cs
> +        public ComponentCssProvider CssProvider { get; } = new();
private

2022-04-11 02:51 UTC, capdiem commented on src/Masa.Blazor/Popup/Components/Toast/Toast.razor.cs
> +        protected void SetComponentClass()
private

2022-04-11 02:51 UTC, capdiem commented on src/Masa.Blazor/Popup/Components/Toast/ToastConfig.cs
> +        public bool IsDark { get; set; } = true;
Why is the IsDark default set to true?

2022-04-11 02:51 UTC, capdiem commented on src/Masa.Blazor/Popup/Components/Toast/Toast.razor.cs
> +    public partial class Toast
主题应该默认使用父组件App的主题(IsDark)，除非此组件手动指定了IsDark。

2022-04-11 02:51 UTC, capdiem commented on src/Masa.Blazor/Popup/Components/Toast/ToastConfig.cs
> +        public Action<string> OnClose { get; set; }
用`Func<string, Task>`会不会通用性强点？

2022-04-11 02:51 UTC, capdiem commented on src/Masa.Blazor/Popup/IPopupService.cs
> +using OneOf;
Unused using.

2022-04-11 02:51 UTC, capdiem commented on src/Masa.Blazor/Popup/IPopupService.cs
> +    event Func<ToastConfig, Task> OnOpening;
`OnConfig` 和 `OnOpening` 应该具体点吧，建议改成`OnToastConfig`

2022-04-11 02:51 UTC, capdiem commented on src/Masa.Blazor/Popup/IPopupService.cs
> +    Task ToastAsync(AlertTypes type, Action<ToastConfig> configAction);
52-53行的`type` 不是可以在ToastConfig里配置吗，为什么要单独拿出来？

2022-04-11 02:51 UTC, capdiem commented on src/Masa.Blazor/Popup/IPopupService.cs
> +    Task ToastAsync(AlertTypes type, string title);
title在前，type在后。

2022-04-11 02:51 UTC, capdiem commented on src/Masa.Blazor/Popup/Components/Toast/Item/ToastItem.razor.cs
> +        public EventCallback<ToastConfig> HandleOnCloseAsync { get; set; }
直接`OnClose`不好吗

2022-04-11 02:51 UTC, capdiem commented on src/Masa.Blazor/Popup/Components/Toast/Item/ToastItem.razor.cs
> +            this.Type = Config.Type;
Config一定不会为null吗？

2022-04-11 02:51 UTC, capdiem commented on src/Masa.Blazor/Popup/Components/Toast/Item/ToastItem.razor.cs
> +                    return "#323d6f";
我觉得你应该通过样式来控制。
例如`.theme-light.m-toast-snackbar {  background-color: #... } `

2022-04-11 02:51 UTC, capdiem commented on src/Doc/Masa.Blazor.Doc/Demos/Components/Presets/children/PopupService/events/Toast.razor
> +            builder.AddContent(0,@<MButton Icon OnClick="HandleOnView">View</MButton>);
Button里套Icon的用法不对。

2022-04-12 05:33 UTC, gavin1ee commented on src/Masa.Blazor/Popup/Components/Toast/Toast.razor.cs
> +        private int? _duration = 400000;
测试时调的.  忘记改回去了

2022-04-24 08:37 UTC, capdiem requested changes

2022-04-24 08:37 UTC, capdiem commented on src/Doc/Masa.Blazor.Doc/Demos/Components/Presets/children/PopupService/events/Toast.razor
> +<MRadioGroup @bind-Value="position" Row>
把`CustomPosition`的操作放在`RadioGroup`值更新时触发。

2022-04-24 09:24 UTC, capdiem approved these changes
LGTM. @doddgu

2022-04-25 02:08 UTC, doddgu approved these changes
LGTM

2022-04-25 02:08 UTC, merged