feat(MDragZone): Support drap &drop
BlazorComponent/MASA.Blazor pull request #488
Opened 2022-05-29 08:46 UTC by Qinyouzeng

Support drap&drop by SorttableJs ,contains the following features:

- sort in a container
- drap&drop between two or more containers
- clone item to other container
- nested
- darg&drop filter

2022-05-30 01:56 UTC, doddgu commented
@capdiem you can review it first, but it will be hold on to 0.5.0.

2022-06-06 01:59 UTC, doddgu requested changes

2022-06-06 01:59 UTC, doddgu commented on src/Masa.Blazor/wwwroot/js/draggable/sorttable-helper.js
> +        onEnd: function (evt) {
remove the space.

2022-06-06 01:59 UTC, doddgu commented on src/Masa.Blazor/wwwroot/js/draggable/sorttable-helper.js
> +            debugger
remove the debugger

2022-06-18 07:47 UTC, capdiem requested changes

2022-06-18 07:47 UTC, capdiem commented on src/Doc/Masa.Blazor.Doc.CLI/appsettings.json
> +      }
rollback this line.

2022-06-18 07:47 UTC, capdiem commented on src/Doc/Masa.Blazor.Doc/Demos/Components/DragZone/doc/index.en-US.md
> +`<script src="https://cdn.masastack.com/npm/sortable/Sortable.min.js"></script>`��
英文下有乱码，文件编码改成utf-8。

2022-06-18 07:47 UTC, capdiem commented on src/Doc/Masa.Blazor.Doc/Demos/Components/DragZone/misc/Clone.razor
> +    .parent {
每个demo样式的名称一样会存在冲突，都加个前缀。

2022-06-18 07:47 UTC, capdiem commented on src/Doc/Masa.Blazor.Doc/Demos/Components/DragZone/misc/Clone.razor
> +        int max = 2, j = 1;
这一堆代码不就是加了一条数据吗？可以精简的。

2022-06-18 07:47 UTC, capdiem commented on src/Doc/Masa.Blazor.Doc/Demos/Components/DragZone/props/Value.razor
> +    {
不就是添加一条数据吗，为啥这么多代码？

2022-06-18 07:47 UTC, capdiem commented on src/Doc/Masa.Blazor.Doc/Demos/Components/DragZone/props/Value.razor
> +        container.Value.Reverse();
反转有问题。

2022-06-18 07:47 UTC, capdiem commented on src/Doc/Masa.Blazor.Doc/Demos/Components/DragZone/props/value.md
> +  zh-CN: 初始化数据
这个例子不像是初始化数据，不太懂。

2022-06-18 07:47 UTC, capdiem commented on src/Masa.Blazor/Components/DragZone/MDragZone.cs
> +        public SorttableOptions Options { get; set; }
建议把SorttableOptions的所有属性平铺到这个组件里，不要用Options和OnConfiguration。

2022-06-22 13:36 UTC, capdiem requested changes

2022-06-22 13:36 UTC, capdiem commented on src/Doc/Masa.Blazor.Doc/Demos/Components/DragZone/doc/index.en-US.md
> +`<script src="https://cdn.masastack.com/npm/sortable/Sortable.min.js"></script>`。
use . instead of 。

2022-06-22 13:36 UTC, capdiem commented on src/Doc/Masa.Blazor.Doc/Demos/Components/DragZone/misc/Nested.razor
> +                    <MDragZone OnConfigure=SetOptions Class="nest-parent nest-item nest-item-1">
`OnConfigure` ?

2022-06-22 13:36 UTC, capdiem commented on src/Masa.Blazor/Components/DragZone/MDragZone.cs
> +        public Action<SorttableOptions> ConfigureOptions { get; set; }
直接叫做 `Options` 吧 🤔

2022-06-24 05:13 UTC, capdiem approved these changes
LGTM @doddgu

2022-06-24 05:24 UTC, doddgu requested changes

2022-06-24 05:24 UTC, doddgu commented on src/Masa.Blazor/Components/DragZone/MDragZone.cs
> +        /// 元素被选中
English

2022-06-24 09:22 UTC, doddgu approved these changes
LGTM

2022-06-24 09:22 UTC, merged