feature(form):fluentValidation support dependencyInjection
BlazorComponent/MASA.Blazor pull request #502
Opened 2022-06-13 09:57 UTC by 15168440402

2022-06-13 10:08 UTC, doddgu commented
@capdiem PTAL

2022-06-14 01:32 UTC, capdiem approved these changes

2022-06-14 03:06 UTC, doddgu requested changes

2022-06-14 03:06 UTC, doddgu commented on src/Doc/Masa.Blazor.Doc/wwwroot/locale/zh-CN.json
> +  "Required": "必填"
必填？必需？

2022-06-14 03:14 UTC, merged