refactor(modal)：add title slot and close slot
BlazorComponent/MASA.Blazor pull request #517
Opened 2022-06-22 08:40 UTC by wzh425

2022-06-22 13:13 UTC, capdiem requested changes

2022-06-22 13:13 UTC, capdiem commented on src/Masa.Blazor/Presets/Modal/ModalBase.razor
> +                             OnClick="HandleOnDelete">
rollback this line.

2022-06-22 13:13 UTC, capdiem commented on src/Masa.Blazor/Presets/Modal/ModalBase.razor
> +                             OnClick="HandleOnCancel">
rollback these lines.

2022-06-22 13:13 UTC, capdiem commented on src/Masa.Blazor/Presets/Modal/ModalBase.razor
> +                             OnClick="HandleOnSave">
rollback these lines.

2022-06-22 13:13 UTC, capdiem commented on src/Masa.Blazor/Presets/Modal/ModalBase.razor.cs
> +        public RenderFragment<(Func<MouseEventArgs, Task> Click, bool Loading)> CloseContent { get; set; }
Loading is not needed.

2022-06-23 02:08 UTC, capdiem approved these changes
LGTM. @doddgu

2022-06-23 06:51 UTC, doddgu approved these changes
LGTM

2022-06-23 06:51 UTC, merged