Added the editing capability of the monaco-editor component
BlazorComponent/MASA.Blazor pull request #820
Opened 2022-11-28 11:38 UTC by 239573049

# Description

_Please explain the changes you've made_

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[issue number]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ x] Code compiles correctly
* [ ] Created/updated tests
* [ x] Extended the documentation

2022-11-30 14:39 UTC, capdiem commented on src/Test/Masa.Blazor.Test/MonacoEditor/MMonacoEditorTests.cs
> +﻿using Microsoft.VisualStudio.TestTools.UnitTesting;
既然是空的就删掉吧

2022-11-30 14:42 UTC, capdiem commented on src/Docs/Masa.Docs.Shared/Components/Markup.razor
> +<AppCode Class="my-0" Rounded="Rounded" Code="@Code" language="@Language" />
这些误改吧，回滚

2022-11-30 14:44 UTC, capdiem commented on src/Docs/Masa.Docs.Shared/Examples/components/monaco-editor/Index.razor
> +            Value = "using System;\r\n"+
为啥不用 @“” ？

2022-11-30 14:45 UTC, capdiem commented on src/Docs/Masa.Docs.Shared/Examples/components/monaco-editor/Index.razor
> +                    "    /* 类名为 HelloWorld */\r\n"+
中文都改成英文。

2022-11-30 14:46 UTC, capdiem commented on src/Docs/Masa.Docs.Shared/Masa.Docs.Shared.csproj
> +
回滚此文件的改动

2022-11-30 14:49 UTC, capdiem commented on src/Masa.Blazor/Components/MonacoEditor/MMonacoEditor.razor
> +﻿@inherits BDomComponentBase
指定namespace为 Masa.Blazor

2022-11-30 14:49 UTC, capdiem commented on src/Masa.Blazor/Components/MonacoEditor/MMonacoEditor.razor.cs
> +namespace Masa.Blazor.Components.MonacoEditor;
指定namespace为 Masa.Blazor

2022-11-30 14:50 UTC, capdiem commented on src/Masa.Blazor/Components/MonacoEditor/MMonacoEditor.razor.cs
> +    public object Option { get; set; } = new { };
不会吧，没有把cv过来的MECharts的代码删掉？

2022-11-30 14:51 UTC, capdiem commented on src/Masa.Blazor/Components/MonacoEditor/Options/EditorFindOptions.cs
> +﻿namespace Masa.Blazor.Components.MonacoEditor.Options;
指定namespace为 Masa.Blazor

2022-11-30 14:51 UTC, capdiem commented on src/Masa.Blazor/Components/MonacoEditor/MonacoEditorJSModule.cs
> +namespace Masa.Blazor.Components.MonacoEditor;
指定namespace为 Masa.Blazor

2022-11-30 14:51 UTC, capdiem commented on src/Masa.Blazor/Components/MonacoEditor/Options/EditorParameterHintOptions.cs
> +﻿namespace Masa.Blazor.Components.MonacoEditor.Options;
指定namespace为 Masa.Blazor

2022-11-30 14:51 UTC, capdiem commented on src/Masa.Blazor/Components/MonacoEditor/Options/EditorMinimapOptions.cs
> +﻿namespace Masa.Blazor.Components.MonacoEditor.Options;
指定namespace为 Masa.Blazor

2022-11-30 14:51 UTC, capdiem commented on src/Masa.Blazor/Components/MonacoEditor/Options/EditorScrollbarOptions.cs
> +﻿namespace Masa.Blazor.Components.MonacoEditor.Options;
指定namespace为 Masa.Blazor

2022-11-30 14:51 UTC, capdiem commented on src/Masa.Blazor/Components/MonacoEditor/Options/HoverOptions.cs
> +﻿namespace Masa.Blazor.Components.MonacoEditor.Options;
指定namespace为 Masa.Blazor

2022-11-30 14:51 UTC, capdiem commented on src/Masa.Blazor/Components/MonacoEditor/Options/KeybindingRule.cs
> +﻿namespace Masa.Blazor.Components.MonacoEditor.Options;
指定namespace为 Masa.Blazor

2022-11-30 14:52 UTC, capdiem commented on src/Masa.Blazor/Components/MonacoEditor/Options/MinimapOptions.cs
> +﻿namespace Masa.Blazor.Components.MonacoEditor.Options;
指定namespace为 Masa.Blazor

2022-11-30 14:52 UTC, capdiem commented on src/Masa.Blazor/Components/MonacoEditor/Options/SuggestOptions.cs
> +﻿namespace Masa.Blazor.Components.MonacoEditor.Options;
指定namespace为 Masa.Blazor

2022-11-30 14:52 UTC, capdiem commented on src/Masa.Blazor/Components/MonacoEditor/Options/TextModelOptions.cs
> +﻿namespace Masa.Blazor.Components.MonacoEditor.Options;
指定namespace为 Masa.Blazor

2022-11-30 14:52 UTC, capdiem commented on src/Masa.Blazor/Extensions/DependencyInjection/ServiceCollectionExtensions.cs
> +using Masa.Blazor.Components.MonacoEditor;
命名空间改了之后，这行Using不需要了。

2022-12-02 07:55 UTC, capdiem requested changes

2022-12-02 07:55 UTC, capdiem commented on src/Docs/Masa.Docs.Shared/Examples/components/monaco-editor/Index.razor
> +            Value = @"using System;\r\n
\r\n 也删掉呀

2022-12-02 07:55 UTC, capdiem commented on src/Docs/Masa.Docs.Shared/Examples/components/monaco-editor/Index.razor
>          {
缩进不对。

2022-12-02 07:55 UTC, capdiem commented on src/Docs/Masa.Docs.Shared/Examples/components/monaco-editor/Index.razor
>      public EditorOptions _EditorOptions { get; set; } = new()
直接用私有变量 _edtiorOptions = new() 不好吗~

2022-12-02 07:55 UTC, capdiem commented on src/Masa.Blazor/Components/MonacoEditor/MMonacoEditor.razor.cs
>      [Parameter] public EditorOptions EditorOptions { get; set; } = new();
[Parameter]后换行

2022-12-12 09:34 UTC, capdiem requested changes

2022-12-12 09:34 UTC, capdiem commented on src/Masa.Blazor/Components/MonacoEditor/MMonacoEditor.razor.cs
> +    private EditorOptions EditorOptions { get; set; } = new();
private??

2022-12-14 13:23 UTC, 239573049 commented on src/Masa.Blazor/Components/MonacoEditor/Options/TextModelOptions.cs
> +public class TextModelOptions
![image](https://user-images.githubusercontent.com/61819790/207606707-1a5414fc-a902-47f8-aefd-1c039aff3e24.png)
他获取的是创建的模型的id

2023-02-03 06:22 UTC, closed without merging