feat: add nav doc
BlazorComponent/MASA.Blazor pull request #826
Opened 2022-12-02 06:52 UTC by codding-y

2022-12-02 07:10 UTC, capdiem requested changes

2022-12-02 07:10 UTC, capdiem commented on src/Docs/Masa.Docs.Shared/wwwroot/pages/about/code-of-conduct/en-US.md
> +order: 3
没有Order

2022-12-02 07:10 UTC, capdiem commented on src/Docs/Masa.Docs.Shared/wwwroot/pages/about/code-of-conduct/en-US.md
> +<br>
<br> 是必须的吗？

2022-12-02 07:10 UTC, capdiem commented on src/Docs/Masa.Docs.Shared/wwwroot/pages/about/meet-the-team/en-US.md
> +<div class="container team-members">
用自定义元素

2022-12-02 07:10 UTC, capdiem commented on src/Docs/Masa.Docs.Shared/wwwroot/pages/features/breakpoints/zh-CN.md
> +<html>
这里一定要html才行吗？可以用自定义元素？试试

2022-12-02 10:40 UTC, capdiem requested changes

2022-12-02 10:40 UTC, capdiem commented on src/Docs/Masa.Docs.Shared/wwwroot/pages/getting-started/brower-support/zh-CN.md
> +<div class="overflow-hidden mb-4 m-sheet m-sheet--outlined theme--light rounded">
use custom elements

2022-12-02 10:40 UTC, capdiem commented on src/Docs/Masa.Docs.Shared/wwwroot/pages/getting-started/brower-support/en-US.md
> +<div class="overflow-hidden mb-4 m-sheet m-sheet--outlined theme--light rounded">
use custom elements

2022-12-02 10:40 UTC, capdiem commented on src/Docs/Masa.Docs.Shared/wwwroot/pages/about/security-disclosure/zh-CN.md
> +<br>
delete <br>

2022-12-05 02:23 UTC, doddgu requested changes

2022-12-05 02:23 UTC, doddgu commented on src/Docs/Masa.Docs.Shared/CircuitRootComponentOptionsExtensions.cs
> +        options.RegisterCustomElement<Masa.Docs.Shared.Examples.getting_started.brower_support.BrowerSupportTable>("brower-support-table");
getting_started? lower case?

2022-12-05 02:23 UTC, doddgu commented on src/Docs/Masa.Docs.Shared/wwwroot/locale/zh-CN.json
> +  "Supported with polyfill": "需要 polyfill",
由 polyfill 支持？

2022-12-05 02:25 UTC, capdiem commented on src/Docs/Masa.Docs.Shared/CircuitRootComponentOptionsExtensions.cs
> +        options.RegisterCustomElement<Masa.Docs.Shared.Examples.getting_started.brower_support.BrowerSupportTable>("brower-support-table");
文件夹名称就是带空格的，用的默认命名空间，所以会用下划线。

2022-12-05 02:33 UTC, capdiem requested changes

2022-12-05 02:33 UTC, capdiem commented on src/Docs/Masa.Docs.Shared/CircuitRootComponentOptionsExtensions.cs
> +        options.RegisterCustomElement<Masa.Docs.Shared.Examples.getting_started.brower_support.BrowerSupportTable>("brower-support-table");
typo: browser

2022-12-05 02:33 UTC, capdiem commented on src/Docs/Masa.Docs.Shared/wwwroot/locale/zh-CN.json
> +  "brower-support": "浏览器支持",
typo: browser

2022-12-05 02:33 UTC, capdiem commented on src/Docs/Masa.Docs.Shared/wwwroot/locale/en-US.json
> +  "brower-support": "Brower support",
typo: browser

2022-12-05 02:33 UTC, capdiem commented on src/Docs/Masa.Docs.Shared/wwwroot/pages/about/security-disclosure/zh-CN.md
> +如果您有关于如何改进这个过程的建议，请使用 <a href="https://github.com/BlazorComponent/Masa.Blazor/issues" target="_blank">issue</a> 请求。
使用 \[link\]()

2022-12-05 02:33 UTC, capdiem commented on src/Docs/Masa.Docs.Shared/wwwroot/pages/about/security-disclosure/en-US.md
> +If you have suggestions on how to improve this process, please submit using <a href="https://github.com/BlazorComponent/Masa.Blazor/issues" target="_blank">issue</a>.
使用 [link]()

2022-12-05 03:11 UTC, capdiem requested changes

2022-12-05 03:11 UTC, capdiem commented on src/Docs/Masa.Docs.Shared/Masa.Docs.Shared.csproj
> +  <ItemGroup>
不需要此ItemGroup

2022-12-05 03:11 UTC, capdiem commented on src/Docs/Masa.Docs.Shared/wwwroot/locale/zh-CN.json
> +  "Extra small": "Extra small (超小号)",
不要偷懒，都用简写的key

2022-12-05 06:00 UTC, capdiem approved these changes

2022-12-05 07:48 UTC, codding-y commented
@doddgu

2022-12-06 06:10 UTC, doddgu requested changes

2022-12-06 06:10 UTC, doddgu commented on src/Docs/Masa.Docs.Shared/wwwroot/pages/about/code-of-conduct/zh-CN.md
> +This Code of Conduct is adapted from the Contributor Covenant, version 1.4, available at https://contributor-covenant.org/version/1/4
？

2022-12-06 06:10 UTC, doddgu commented on src/Docs/Masa.Docs.Shared/wwwroot/pages/about/meet-the-team/zh-CN.md
> +<team-members name="王增星"
Replace to you.

2022-12-06 06:50 UTC, doddgu approved these changes
LGTM

2022-12-06 06:51 UTC, merged