fix(ErrorHandler): custom error handle loop render
BlazorComponent/MASA.Blazor pull request #848
Opened 2022-12-19 10:26 UTC by Qinyouzeng

2022-12-20 10:59 UTC, doddgu commented
@Qinyouzeng Azure Static Web Apps CI/CD v1 / Build and Deploy Job (pull_request) Failing after 2m

2022-12-22 02:28 UTC, capdiem approved these changes
LGTM @doddgu

2022-12-22 02:29 UTC, capdiem requested changes

2022-12-22 02:29 UTC, capdiem commented on src/Doc/Masa.Blazor.Doc/Demos/Components/ErrorHandler/props/onErrorHandleAsync.md
> +自定义异常处理`Func<Exception,Task<bool>>`，点击按钮触发异常后，按钮背景色变为红色文字颜色改为白色。
新文档没改！

2022-12-23 07:11 UTC, doddgu approved these changes
LGTM

2022-12-26 01:34 UTC, doddgu requested changes

2022-12-26 01:34 UTC, doddgu commented on src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MErrorHandler.zh-CN.json
> +      "Type": "Func<Exception,Task`1>",
`1?

2022-12-26 05:15 UTC, Qinyouzeng commented on src/Doc/Masa.Blazor.Doc/wwwroot/docs/api/MErrorHandler.zh-CN.json
> +      "Type": "Func<Exception,Task`1>",
This is an old document, don't care .

2022-12-26 05:57 UTC, merged