feat: Add MBaiduMap component
BlazorComponent/MASA.Blazor pull request #951
Opened 2023-01-21 12:16 UTC by msnoshain

# Description

Add MBaiduMap component to enable essential map services. 
To use map service, register your service key (ak) [here](https://lbsyun.baidu.com/index.php?title=jspopularGL/guide/getkey).

Once you've got your key, you can add  a map in your blazor page like:
`<MBaiduMap ServiceKet="your-key" />`

Only a few features supported by now. More features will be supported in the future.
Only BaiduMap Service supported by now. More service providers will be supported in the future.

2023-01-22 16:01 UTC, capdiem requested changes

2023-01-22 16:01 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +            if (firstRender && !jsHasInjected)
`jsHasInjected` 这个变量感觉不是必须的，可以删除吧

2023-01-22 16:01 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +            if (!firstRender && !mapHasLoaded)
把第二次render的代码放在第一次Render里，使用NextTick

2023-01-22 17:54 UTC, msnoshain commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +                    throw new ArgumentNullException
我已经把ServiceKey用EditorRequired特性标记了，如果不填写vs会产生警告。不过如果有更好的办法的话麻烦您指出，我再去修改☺️

2023-01-22 18:01 UTC, msnoshain commented on src/Masa.Blazor/Components/Map/BaiduMap/BaiduMapJSModule.cs
> +        => await InvokeVoidAsync("injectBaiduMapScript", serviceKey);
我看echart的jsmodule中也是左对齐，就抄过来了。所以这里应该有缩进才对。

2023-01-22 18:03 UTC, msnoshain commented on src/Masa.Blazor/Components/Map/BaiduMap/BaiduMapJSModule.cs
> +        public async ValueTask LoadMapAsync(string divID, (bool canZoom, byte zoom, PointF mapCenter) args)
考虑到需要初始化的参数比较多，这里可能使用MapInitOption代替此元组，来进行地图初始化的参数配置会更好

2023-01-22 18:23 UTC, msnoshain commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +            if (firstRender && !jsHasInjected)
> `jsHasInjected` 这个变量感觉不是必须的，可以删除吧

这的确是个多余的变量，可以移除

2023-01-23 01:52 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +                    throw new ArgumentNullException
ServiceKey 不存在的话就在 razor 页面提示一下就行吧，报异常会让整个页面挂掉

2023-01-23 06:53 UTC, msnoshain commented
代码修改已完成 @capdiem

2023-01-23 06:54 UTC, msnoshain commented
代码修改已完成 @capdiem

2023-01-23 09:50 UTC, capdiem requested changes

2023-01-23 09:50 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +                StateHasChanged();
放在 nextick 之后

2023-01-23 09:50 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +                    if (Module is null || mapHasLoaded)
module 在此肯定不会为空，也不用 maphasloaded，用 jsmap 就行了。

2023-01-23 09:50 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +        ElementReference? jsMap;
```suggestion
        IObjectReference? _mapObjectReference;
```

2023-01-23 09:50 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +        /// Inject BaiduMap Javascript code and load map. Click
这个注释不对，你可以写在方法体内。OnAfterRender 不用写注释

2023-01-23 09:54 UTC, capdiem commented
Map 的 options 改动之后这块你还没有做，比如 CanZoom 和 Zoom 参数，需要 watch ，监听改动，再通知到 js。

2023-01-24 06:28 UTC, capdiem requested changes

2023-01-24 06:28 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +                if (val == MapCenter)
不用判断， val 是更改后的值

2023-01-24 06:28 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +                await Module.InjectBaiduMapScriptAsync(ServiceKey);
放在 nexttick 之前语义上比较合理

2023-01-24 06:28 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/BaiduMapJSModule.cs
> +        public async ValueTask<IJSObjectReference> LoadMapAsync(string containerID, BaiduMapInitOption args)
```suggestion
        public async ValueTask<IJSObjectReference> LoadMapAsync(string containerId, BaiduMapInitOption args)
```

2023-01-24 06:28 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/BaiduMapJSModule.cs
> +        public async ValueTask<IJSObjectReference> LoadMapAsync(string containerID, BaiduMapInitOption args)
```suggestion
        public async ValueTask<IJSObjectReference> LoadMapAsync(string containerID, BaiduMapInitOptions options)
```

2023-01-24 06:28 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +                if (val == CanZoom)
不要判断

2023-01-24 06:28 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +                if (val != Zoom)
不用判断

2023-01-24 09:28 UTC, capdiem requested changes

2023-01-24 09:28 UTC, capdiem commented on src/Masa.Blazor.Playground/Pages/Index.razor
> +<MBaiduMap ServiceKey="QahcSGCkRzIVXBkKhWHt3vGhNyYGdk3t"
把文档的 demo 补一下。playground 不动。

2023-01-24 09:28 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/BaiduMapJSModule.cs
> +                    new
直接把 options 传给JS呀。

2023-01-26 07:31 UTC, capdiem requested changes

2023-01-26 07:31 UTC, capdiem commented on src/Docs/Masa.Blazor.Docs/Masa.Blazor.Docs.csproj
> +  <ItemGroup>
此 ItemGroup 删掉。

2023-01-26 07:31 UTC, capdiem commented on src/Docs/Masa.Blazor.Docs/wwwroot/pages/components/baidumaps/en-US.md
> +Before using BaiduMap services, go to [BaiduMap Open Platform](https://lbs.baidu.com/index.php?title=jspopularGL/guide/getkey) to register a
```suggestion
Before using BaiduMap services, go to [BaiduMap Open Platform](https://lbs.baidu.com/index.php?title=jspopularGL/guide/getkey) to register a 
```
```suggestion
Before using the **MBaiduMap** component, go to [BaiduMap Open Platform](https://lbs.baidu.com/index.php?title=jspopularGL/guide/getkey) to register a 
```

2023-01-26 07:31 UTC, capdiem commented on src/Docs/Masa.Blazor.Docs/wwwroot/pages/components/baidumaps/en-US.md
> +`<script src="https://api.map.baidu.com/api?v=1.0&&type=webgl&ak={your-AK}"></script>`
用代码块吧，三个 ` 。

2023-01-26 07:31 UTC, capdiem commented on src/Docs/Masa.Blazor.Docs/wwwroot/pages/components/baidumaps/zh-CN.md
> +在使用百度地图服务前，首先需要到[百度地图开放平台](https://lbs.baidu.com/index.php?title=jspopularGL/guide/getkey)注册开发者账号，并申请AK。
```suggestion
在使用百度地图服务前，首先需要到[百度地图开放平台](https://lbs.baidu.com/index.php?title=jspopularGL/guide/getkey)注册开发者账号，并申请AK。
```
```suggestion
在使用**MBaiduMap**组件前，首先需要到[百度地图开放平台](https://lbs.baidu.com/index.php?title=jspopularGL/guide/getkey)注册开发者账号，并申请AK。
```

2023-01-26 07:31 UTC, capdiem commented on src/Docs/Masa.Blazor.Docs/wwwroot/pages/components/baidumaps/zh-CN.md
> +`<script src="https://api.map.baidu.com/api?v=1.0&&type=webgl&ak={your-AK}"></script>`
使用代码块。

2023-01-26 07:31 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/BaiduMapInitOption.cs
> +    public class BaiduMapInitOption
```suggestion
    public class BaiduMapInitOption
```
```suggestion
    public class BaiduMapInitOptions
```

2023-01-26 07:31 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +        public StringNumber Height { get; set; } = 240;
加个Attribute：`[DefaultValue(xx)]`，下面有自定义默认值的都加上。

2023-01-26 07:31 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +        [EditorRequired]
DarkThemeId不用EditorRequired吧

2023-01-26 07:31 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +        //public EventCallback<float> OnZoomChanged { get; set; }
注释？不用删掉

2023-01-26 07:31 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +        public void OnJsZoomEnd(object zoomJson)
直接用`float`接不就好了？

2023-01-26 07:31 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +        public void OnJsMoveEnd(object pointJson)
直接用对象接，大不了再搞个BaiduMapPoint类代替PointF。

2023-01-26 07:42 UTC, capdiem requested changes

2023-01-26 07:42 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +                    await JsMap.InvokeVoidAsync("disableScrollWheelZoom");
```suggestion
                await JsMap.InvokeVoidAsync(val ? "enableScrollWheelZoom" : "disableScrollWheelZoom");
```

2023-01-26 07:42 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +                    await JsMap.InvokeVoidAsync("setMapStyleV2", new { StyleId = string.Empty });
```suggestion
                await JsMap.InvokeVoidAsync("setMapStyleV2", new { StyleId = val ? DarkThemeId : string.Empty });
```

2023-01-26 07:42 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +                ObjRef = DotNetObjectReference.Create(this);
ObjRef需要释放。

2023-01-26 07:42 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +                JsMap = await Module.InitMapAsync(Id, new BaiduMapInitOption()
JsMap需要释放。

2023-01-26 07:42 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +        private bool ZoomChangedInJs = false;
```suggestion
        private bool _zoomChangedInJs = false;
```

2023-01-26 07:42 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +        private bool CenterChangedInJs = false;
```suggestion
        private bool _centerChangedInJs = false;
```

2023-01-26 07:42 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +        private DotNetObjectReference<MBaiduMap> ObjRef { get; set; }
```suggestion
        private DotNetObjectReference<MBaiduMap> _objRef;
```

2023-01-26 07:42 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +        private JsonSerializerOptions SerializerOptions = new();
```suggestion
        private JsonSerializerOptions _serializerOptions = new();
```

2023-01-26 07:42 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +        private IJSObjectReference JsMap { get; set; }
```suggestion
        private IJSObjectReference _jsMap;
```

2023-01-26 07:42 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +    public partial class MBaiduMap : BDomComponentBase, IThemeable, IMap
```suggestion
    public partial class MBaiduMap : BDomComponentBase, IThemeable, IMap, IAsyncDispose
```

2023-01-26 07:42 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +                StateHasChanged();
应该不需要`StateHasChanged`

2023-01-26 13:59 UTC, msnoshain commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +        public void OnJsMoveEnd(object pointJson)
这里直接用对象接会有属性名大小写的问题，js传过来的属性名首字母都是小写。必须要用object接，然后反序列化时手动设置忽略大小写

2023-01-27 10:05 UTC, capdiem requested changes

2023-01-27 10:05 UTC, capdiem commented on src/Masa.Blazor/Components/Map/DataConverterExtension.cs
> +    public static class DataConverterExtension
用不上了吧？

2023-01-27 10:05 UTC, capdiem commented on src/Masa.Blazor/Components/Map/GeoPoint.cs
> +        public PointF ToPointF() => new (Lng, Lat);
这个还有用？

2023-01-27 14:02 UTC, capdiem approved these changes
LGTM @doddgu

2023-01-29 07:19 UTC, doddgu approved these changes
LGTM，thanks for pr

2023-01-29 07:19 UTC, merged