feat: Support for dynamic theme modification
BlazorComponent/MASA.Blazor pull request #952
Opened 2023-01-22 06:55 UTC by LittleFish-233

# Description
之前的行为：
在 `MApp` 组件初始化时，使用 `JS` 添加 `styles`，无法动态修改

修改后的行为：
在  `MApp` 组件内部添加内联CSS，即使预渲染状态下无法使用 `JS` ，也可以确保正确生成预配置样式
修改 `MasaBlazor` 服务的 `Theme ` 属性为可写，并添加 `Action` 通知 `MApp` 组件样式已修改，重新生成内联CSS

组件库的文档没有适配深色模式，我也不熟悉组件库文档站点，所以没有同步修改适配，还请见谅

Machine translation: 

previous behavior:
When the `MApp` component is initialized, `styles` are added with `JS` and cannot be modified dynamically

Modified behavior:
Adding inline CSS inside the `MApp` component ensures that preconfigured styles are generated correctly even if `JS` is not available in the pre-rendered state
Modify the `Theme` property of the `MasaBlazor` service to be writable, and add `Action` to notify the `MApp` component style has been modified and regenerate the inline CSS

The documentation of the component library does not adapt to dark mode, and I am not familiar with the component library documentation site, so I did not modify the adaptation synchronously, please forgive me

## Issue reference

#929 

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Extended the documentation

It was not clear where the unit tests were, so it was not written

2023-01-22 16:11 UTC, capdiem requested changes

2023-01-22 16:11 UTC, capdiem commented on src/Docs/Masa.Blazor.Docs/Masa.Blazor.Docs.csproj
> +  <ItemGroup>
删除此 ItemGroup

2023-01-22 16:11 UTC, capdiem commented on src/Masa.Blazor/Components/App/MApp.cs
> +        private void MasaBlazor_OnThemeChange(Theme theme)
```suggestion
        private void OnThemeChange(Theme theme)
```

2023-01-22 16:22 UTC, capdiem commented
对于把 css 写在 body 里我是无法定义风险的 😄

2023-01-23 01:38 UTC, LittleFish-233 commented
如果需要的话，也可以像内置组件 [HeadOutlet](https://learn.microsoft.com/zh-cn/aspnet/core/blazor/components/control-head-content?view=aspnetcore-7.0#headoutlet-component) 一样，创建一个 `ThemeProvider` 组件放在 `head` 里。但是需要用户额外添加代码，所以没有选择这个方案

之前也会通过 `js` 动态插入 `<style>`，我个人认为安全风险应该是一样的

2023-01-23 02:00 UTC, capdiem commented
直接使用`HeadContent`组件可以吗？

2023-01-23 02:01 UTC, LittleFish-233 commented
同一个页面下只有一个 `HeadContent` 组件实例会生效，可能会覆盖用户自己的 `PageTitle`

2023-01-23 02:07 UTC, capdiem commented
JS 插入 head 其实还好吧，不会有啥风险

2023-01-23 02:23 UTC, LittleFish-233 commented
确实，同样把 `<style>` 写在 `body` 里应该也没有什么风险吧

2023-01-23 02:33 UTC, capdiem commented
没，就是不太规范😂 @doddgu 你觉得呢

2023-01-29 03:55 UTC, doddgu commented
#929 提到的意思应该是除了dark和light以外的自定义主题模板的支持？
另外支持的方式我前几天看了个办法，通过css的变量来调整，但这个可能会对现有css大改，我不确定 你看呢 @capdiem 

参考: 【两分钟搞懂CSS Variables-哔哩哔哩】 https://b23.tv/yxfTZCt
【Theming Tailwind with CSS Variables-哔哩哔哩】 https://b23.tv/PI1B4iu

2023-01-29 04:53 UTC, capdiem commented
Vuetify3 好像是 css variables 了。

2023-01-29 05:05 UTC, LittleFish-233 commented
> #929 提到的意思应该是除了dark和light以外的自定义主题模板的支持？

也支持动态修改自定义主题模板，组件库里没有颜色选择器，所以示例就是简单的浅色深色切换

是否使用 css variables 都行，毕竟最后都需要通过js或其他方式插入styles。而且对现有css大改可能耗时很久，可以先使用现在的方案。

2023-01-29 07:41 UTC, doddgu commented
我觉得可以先按照这一版简化动态主题生效的部分代码。在开发2.0的时候，考虑对vuetify 3的支持，把css也升上去，但可能会需要一个大的重构来兼容vuetify 3。这将是MASA Blazor 2.0第一个版本的重要里程碑

2023-01-31 01:35 UTC, LittleFish-233 commented
GitHub客户端显示没有冲突，请问一下应该怎么办？
![image](https://user-images.githubusercontent.com/53342258/215636726-979915c6-7ba5-4856-ad3e-3e7541bf5d9b.png)

2023-02-03 00:27 UTC, LittleFish-233 commented
我按照下述操作
1. 将fork的repo拉取到最新
2. 本地clone上一步fork的repo
3. 把main再拉取一次
4. 把工作分支合并到main

仍然显示无冲突

2023-02-03 05:53 UTC, doddgu requested changes

2023-02-03 05:53 UTC, doddgu commented on src/Docs/Masa.Blazor.Docs/Examples/components/application/DynamicallyModifyTheme.razor
> +﻿<MSwitch Value="IsDark" TValue="bool" ValueChanged="IsDarkChanged" Label="@(IsDark?"深色模式":"浅色模式")"/>
English or I18n is recommended for label.

2023-02-03 06:00 UTC, doddgu approved these changes
LGTM

2023-02-03 06:13 UTC, merged