🆕 feat(MBaiduMap): Support more properties; Fix docs
BlazorComponent/MASA.Blazor pull request #975
Opened 2023-02-03 09:23 UTC by msnoshain

# Description

Fix docs and support following properties: 

* [ ] MaxZoom
* [ ] MinZoom
* [ ] MapType
* [ ] TrafficOn

2023-02-03 09:27 UTC, doddgu commented
@capdiem PTAL

2023-02-03 10:05 UTC, capdiem requested changes

2023-02-03 10:05 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +                if (_jsMap is null)
几乎每个watch都要判断`_jsMap`，重构一下

2023-02-03 10:05 UTC, capdiem commented on src/Masa.Blazor/Components/Map/Models/MapTypes.cs
> +    public static class MapTypeNameMapping
私有的就行了，放在razor.cs。

2023-02-03 16:28 UTC, msnoshain commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +        [DefaultValue(false)]
这里不写的话文档显示不出来

2023-02-04 03:06 UTC, capdiem requested changes

2023-02-04 03:06 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +            Watcher.Watch<bool>(nameof(TrafficOn),
仍然比较复杂，加个扩展方法，放在BlazorComponent的Extensions文件夹下：
``` c#
public static class IJSObjectReferenceExtensions
{
    public static async ValueTask TryInvokeVoidAsync(this IJSObjectReference? jsObjectReference, string identifier, params object?[]? args)
    {
        if (jsObjectReference is null)
        {
            return;
        }

        await jsObjectReference.InvokeVoidAsync(identifier, args);
    }
}
```

2023-02-04 03:07 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +        [DefaultValue(false)]
那是文档的问题 😆

2023-02-04 08:58 UTC, capdiem approved these changes
LGTM

2023-02-05 05:36 UTC, merged