🆕 feat(MBaiduMap): Map overlays
BlazorComponent/MASA.Blazor pull request #989
Opened 2023-02-08 03:09 UTC by msnoshain

# Description

Support map overlays and main interactions (add, remove and clear).

## Progress

See progress in the following list:

* [ ] Marker
* [ ] Label
* [ ] Polyline
* [ ] Polygon
* [ ] Circle

More advanced overlays will be supported in the future (Icon, Symbol, SVGSymbol and so on).

2023-02-09 16:21 UTC, capdiem requested changes

2023-02-09 16:21 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +        }
两次调用JS可以合并成一个，即 `addOverlay` 之后把 `overlay` 的 ref 传回来。

2023-02-09 16:21 UTC, capdiem commented on src/Masa.Blazor/Masa.Blazor.csproj
> +	</ItemGroup>
删除

2023-02-09 16:21 UTC, capdiem commented on src/Masa.Blazor/Components/Map/Abstractions/Overlays/IMapOverlay.cs
> +    public interface IMapOverlay<TMap> where TMap : IMap
我怎么觉得应该用 `abstract` 才对？

2023-02-16 02:11 UTC, capdiem requested changes

2023-02-16 02:11 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/Extentions/JSProxyExtentions.cs
> +            await origin.InvokeVoidAsync(identifier, args);
这个方法走了两次JS互操作，我看调用方是为了调用原生的API，其实你可以在 **BaiduMapProxy** 类中再写一遍那些方法。例如：
``` js
setZoom(val) {
  this.instance.setZoom(val);
}
```

2023-02-16 02:11 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor
> +<CascadingValue Value="this" Name="Parent" TValue="MBaiduMap">
不需要设置 Name，子组件可以直接拿到的。

2023-02-16 02:11 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +            await _baiduMap.TryInvokeOriginVoidAsync("addOverlay", overlay.OverlayRef);
怎么又发开了，合并成一个呀

2023-02-16 03:23 UTC, capdiem requested changes

2023-02-16 03:23 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/BaiduMapJSObjectReferenceProxy.cs
> +    public async ValueTask<IJSObjectReference> InitAndAddOverlayAsync(MBaiduOverlay overlay)
方法名改成 `AddOverlayAsync`

2023-02-16 03:31 UTC, capdiem requested changes

2023-02-16 03:31 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/BaiduMapJSObjectReferenceProxy.cs
> +        }
在Callbacks里定义一个`HandleOnZoomEnd`方法，这里直接调`_owenr.HandleOnZoomEnd`好了，MBaiduMap实现HandleOnZoomEnd，在里面调用NotifyZoomChangedInJs和OnZoomEnd的逻辑。

2023-02-16 05:06 UTC, capdiem requested changes

2023-02-16 05:06 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/IBaiduMapJSObjectReferenceProxy.cs
> +        Func<Task> NotifyZoomChangedInJS { get; set; }
Notify这些应该用不上了吧

2023-02-16 05:06 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +                _baiduMap.NotifyZoomChangedInJS = async () =>
逻辑直接写在`HandleOnSetZoom`里

2023-02-16 14:44 UTC, capdiem requested changes

2023-02-16 14:44 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/Overlays/MBaiduOverlay.cs
> +        public virtual MBaiduMap MapRef { get; set; }
```suggestion
        protected MBaiduMap BaiduMap { get; set; }
```

2023-02-16 14:44 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/Overlays/MBaiduOverlay.cs
> +        public virtual IJSObjectReference OverlayRef { get; set; }
```suggestion
        internal IJSObjectReference OverlayJSObjectRef { get; set; }
```

2023-02-16 14:44 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/Overlays/MBaiduOverlay.cs
> +        public async Task ShowAsync() => await OverlayRef.InvokeVoidAsync("show");
```suggestion
        public async Task ShowAsync() => await OverlayRef.TryInvokeVoidAsync("show");
```

2023-02-16 14:44 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/Overlays/MBaiduOverlay.cs
> +        public async Task HideAsync() => await OverlayRef.InvokeVoidAsync("hide");
```suggestion
        public async Task HideAsync() => await OverlayRef.TryInvokeVoidAsync("hide");
```

2023-02-16 14:44 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/Overlays/MBaiduPolygon.cs
> +                NextTick(async () => await MapRef.AddOverlayAsync(this));
```suggestion
                NextTick(async () => OverlayJSObjectRef = await MapRef.AddOverlayAsync(this));
```

2023-02-16 14:44 UTC, capdiem commented on src/Masa.Blazor/Components/Map/BaiduMap/MBaiduMap.razor.cs
> +                await _baiduMap.TryInvokeVoidAsync("addOverlay", overlay.OverlayRef);
```suggestion
            return _baiduMap.AddOverlayAsync(overlay);
```

2023-02-21 04:13 UTC, doddgu commented
Is there any progress? And it need to resolve conflicts.

2023-02-21 06:03 UTC, msnoshain commented
> Is there any progress? And it need to resolve conflicts.

Writing docs

2023-02-21 09:28 UTC, closed without merging